### ISSUE TITLE
Error on function call

### ISSUE THREAD

**Issue by Blatman** [devrafalko/list-contents#1]
Not sure how to get this going - tried 

var list = require('list-contents');

list("./local",(data)=>{
  if(data.error) throw data.error;
  console.log('Folders: ', data.dirs);
  console.log('Files: ', data.files);
});

I guess this calls a function in the list-contents module but get the following error -

<img width="1137" alt="error" src="https://user-images.githubusercontent.com/11089335/93256962-15222080-f794-11ea-9887-7015f8d02e41.png">

The ./local is a folder co-existing with the .js file

Cheers.

**Comment by devrafalko** [comment]
I've copied the code to the `index.js` file, run it with `node index.js` command and it works fine. Do you use some bundlers, etc.?

**Comment by Blatman** [comment]
Thanks Pawel,
obviously runs in node context at your end and I think my issue could be that it was being run from a browser context.
I am using NW.js (as desktop app) to run my index.html page which calls the app.js file in the <script> tags (browser context). Normally within the app.js file you can require node modules and they will work because NW.js provides a connection to the node context from the browser context but in this case it doesn't work.
Rather than require the module from my app.js file I tried referencing the index.js from my index.html via script tags and I got the console logs but there was a 'ReferenceError: module not defined' at line 8 in the index.js

I will need to look closer at my contexts because normally the node module would be accessible using require (or nw.require) - maybe it is something in how I am calling the function.
